name: Build WAM

on:
  workflow_dispatch
#   push:
#     tags:
#       - "v*"

env:
  PROJECT_NAME: TemplateProject
  URL: https://${{github.repository_owner}}.github.io/${{github.event.repository.name}}/

jobs:
  build:
    name: Build-WAM
    runs-on: ubuntu-latest
  
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false

      - name: setup python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          actions-cache-folder: 'emsdk-cache'

      - name: Patch emcc.py
        run: |
          sed -i.bak s,"if not js_manipulation.isidentifier(settings.EXPORT_NAME):","if False:",g $EMSDK/upstream/emscripten/emcc.py
        shell: bash

      - name: Get WAM SDKS
        run: |
          cd iPlug2/Dependencies/IPlug
          ./download-iplug-sdks.sh
        shell: bash

      - name: Compile WAM
        run: |
          cd ${{env.PROJECT_NAME}}/scripts
          ./makedist-web.sh off ${{env.URL}}
          
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.PROJECT_NAME}}-web
          path: ${{env.PROJECT_NAME}}/build-web

      - name: Publish to pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: ${{env.PROJECT_NAME}}/build-web
